### ISSUE TITLE
Person Template: Graph is too fat if the person has only 1 article

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#27]
The graph should not rescale with the data.

e.g. : http://openbiodiv.net/e953281a-613b-41ec-91c8-736da3411693
Name: Andreas Müller

The ultimate solution is to fix the length of either the X or Y axis.

For example we can fix the X axis to 2010 to 2017 (but this is not good as we might have more years)

Or if we flip the graph so that the X axis is number of articles, then we need to fix to 0..20 (and ignore if someone has more than 20 article, which is highly unlikely)

@teodorgeorgiev @howkins  what do you think?

Best

**Comment by pdatascience** [comment]
@howkins if you point me to where in the code the graph is generated I can play with the best settings. :)

**Comment by howkins** [comment]
is waiting to be deploy on production

**Comment by howkins** [comment]
part of fix to deploy @teodorgeorgiev
