### ISSUE TITLE
Misinterpretaion of certain queries

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#29]
Certain queries are misinterpreted. For example when the user types "Page" meaning a last name, he or she gets an empty page as the ontology element `foaf:page` is matched. Better would be in this case to 

(a) display Alternative Implementation component is displayed
(b) display `foaf:Page` in the generic template header (even if it still empty)

![image](https://user-images.githubusercontent.com/12908070/31251602-ce6124c2-aa1e-11e7-8b75-85b6fbed8017.png)

**Comment by pdatascience** [comment]
please, comment @teodorgeorgiev

**Comment by pdatascience** [comment]
![image](https://user-images.githubusercontent.com/12908070/31252799-ad475cb2-aa22-11e7-8efd-13f69a10bfe5.png)

**Comment by howkins** [comment]
to deploy @teodorgeorgiev @pdatascience
