### ISSUE TITLE
Subpage for the Ontology and Guide

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#32]
Since JBS Paper, we need to not have Under Construction on the site.

This issue deals with the Ontology on the homepage of OpenBiodiv.

**Solution** When the user clicks on Ontology they should be redirected to

`http://openbiodiv.net/openbiodivo-20171103`

Then, if they are a web-browser, the HTML file under

[website/openbiodivo-20171103.html](../blob/master/website/openbiodivo-20171103.html) should be rendered.

If, however, "application/rdf+xml" is requested, they should receive

[website/openbiodivo-20171103.xml](../blob/master/website/openbiodivo-20171103.xml)

**Comment by pdatascience** [comment]
@howkins  Looks excellent, thank you! Also RDF content-type works which is great.

Two quick follow-ups:

1. Is it possible to have the sources scroll down, instead of sideways?
2. Is the framework flexible, os that the HTML file can be replaced from time to time? I intend to regenerate it on Friday to fix bugs (broken links, etc.). Would it be difficult to replace?

Best
Viktror

**Comment by howkins** [comment]
@pdatascience 

1. The sources code it is possible to be scroll down and I fixed it with the help of  css `white-space: pre-line;`
2. At that moment is not possible to be flexible this page. Could you give me the new html. I must to revalidate it again.
