### ISSUE TITLE
Alternative Interpretation + Title Improvements

### ISSUE THREAD

**Issue by pdatascience** [pensoft/OpenBiodiv#34]

**Comment by pdatascience** [comment]
Make Alternative Interpretation More User- Understandable

**Comment by howkins** [comment]
[ ] 1. Title to display _current_ interpretation. Label + Type. E.g. "Pavel Stoev (Person)"
[ ] 2. Arrow to indicate that alternative interpretation is expandable.
[ ] 3. Same as (1) for the sub-items of 2. E.g. alternative interpretation: "Pavel stoevi (taxonomic concept)"

Possible solution for 1:
- only display objects with template
- choose type with maximum depth
- TODO @pdatascience : add depth property to interesting types

**Comment by howkins** [comment]
To deploy @teodorgeorgiev
