### ISSUE TITLE
The URL http://openbiodiv.net/ontology/ yields a 404

### ISSUE THREAD

**Issue by hlapp** [pensoft/OpenBiodiv#35]
Reference [45] in [Senderov _et al_ (2018)](https://doi.org/10.1186/s13326-017-0174-5) is given as the following for the literate programming-encoded version of the ontology:

> Senderov V, Franz NM, Simov K. OpenBiodiv Ontology and Guide. 2017. http://openbiodiv.net/ontology. Accessed 09 Aug 2017.

However, this URL yields a 404.

**Comment by pdatascience** [comment]
@howkins could you please forward <http://openbiodiv.net/ontology> to the latest version 

<http://openbiodiv.net/openbiodivo-20171103>

- [] web browser 
- [] RDF/XML

**Comment by howkins** [comment]
to deploy

**Comment by pdatascience** [comment]
deployed...
