### ISSUE TITLE
Ontology IRI does not resolve to RDF/XML

### ISSUE THREAD

**Issue by hlapp** [pensoft/OpenBiodiv#43]
I thought http://openbiodiv.net/ontology/ is the canonical IRI for the OpenBiodiv-O ontology, but if so, it only resolves to HTML, even if `application/rdf+xml` is requested:

```sh
$ curl -D - -s -o /dev/null -H "Accept: application/rdf+xml" http://openbiodiv.net/ontology/
HTTP/1.1 200 OK
Date: Tue, 11 Dec 2018 22:03:16 GMT
Server: Apache/2.4.25 (Debian)
X-Powered-By: PHP/7.0.30-0+deb9u1
Set-Cookie: PHPSESSID=2953qaofang4jsun7a6fh7rh75; path=/; domain=.openbiodiv.net
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Cache-Control: no-cache, private
Set-Cookie: laravel_session=eyJpdiI6IjdRZFZld040a2t4YWR6N1Z5SEF4SkE9PSIsInZhbHVlIjoiNklyR1A5NG9pVzNQbld2VU0wYmkxaVlKRVwvWnhqK2FzbGhOaVpIeko0eFRDc2xTSXJmK3ZXbzE3K2RkTWhJZlB1NFJPSDZDaHpmRTZ6QTdTeDkzWHFRPT0iLCJtYWMiOiI0MDdjZDc2ODNiM2RiZWM1MmI4MDRlZGVkYWJhOGVhM2M2N2YwZTFlMWQ1NjVjYjcyMjhkMjIwY2ZkZTVmZTczIn0%3D; path=/; httponly
Vary: Accept-Encoding
Content-Length: 1513
Content-Type: text/html; charset=UTF-8
```
(It isn't lying about what is returned -- it really does return an HTML page.)

If the [ontology/openbiodiv-ontology.ttl](https://github.com/pensoft/OpenBiodiv/blob/master/ontology/openbiodiv-ontology.ttl) file in the repo is the authoritative version of the ontology (is it?), it seems to give http://openbiodiv.net/openbiodiv-ontology/ as the ontology's IRI, not the one above. However, dereferencing it has the same result.

**Comment by howkins** [comment]
Hi @hlapp we resolved this issue. Please try again.

**Comment by hlapp** [comment]
Thanks, looks like this works now. Note that the returned content type is announced as `application/xml`. That's obviously not wrong, but isn't the same as requested (`application/rdf+xml`), and `application/rdf+xml` would be specific.
